#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }

vecho "Add ${S6_USER:-alpine} to groups: dialout, video";

if [ -n "${GID_DIALOUT}" ]; # update gid of 'dialout' if defined
then
    groupmod -o -g "${GID_DIALOUT}" dialout;
fi;

if [ -n "${GID_VIDEO}" ]; # update gid of 'video' if defined
then
    groupmod -o -g "${GID_VIDEO}" video;
fi;

adduser ${S6_USER:-alpine} dialout;
adduser ${S6_USER:-alpine} video;

if [ -n "${WAIT_FOR_HDMI_CONNECT}" ];
then
    WAIT_SEC="${WAIT_SEC:-10}";
    vecho 'Waiting for HDMI connection.';
    until \
      cat /sys/class/drm/card*/*HDMI*/status 2>/dev/null \
      | grep -q '^connected';
      do echo -n ' .'; sleep ${WAIT_SEC}; done;
    vecho 'Connected.';
fi;
