#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }

if [ "X${EUID}" == "X0" ]; # requires root
then
    vecho "Add ${S6_USER:-alpine} to groups: dialout, video";
    if [ -n "${GID_DIALOUT}" ]; # update gid of 'dialout' if defined
    then groupmod -o -g "${GID_DIALOUT}" dialout;
    fi;
    adduser ${S6_USER:-alpine} dialout;
    if [ -n "${GID_VIDEO}" ]; # update gid of 'video' if defined
    then groupmod -o -g "${GID_VIDEO}" video;
    fi;
    adduser ${S6_USER:-alpine} video;
fi;
